LOT5RDB/Models/ErrorViewModel.cs
namespace LOT5RDB.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

LOT5RDB/Models/SkillsViewModel.cs
using LOT5RDB.Skills.Shared.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LOT5RDB.Models;

public class SkillsViewModel : PageModel
{
    public SkillsViewModel(List<SkillModel> items, int count, int pageIndex, int pageSize)
    {
        PageIndex = pageIndex;
        TotalPages = (int) Math.Ceiling(count / (double) pageSize);

        Skills = items;
    }

    public int PageIndex { get; private set; }
    public int TotalPages { get; private set; }
    public bool HasPreviousPage => PageIndex > 1;

    public bool HasNextPage => PageIndex < TotalPages;
    public List<SkillModel> Skills { get; set; }

    public static SkillsViewModel Create(List<SkillModel> source, int pageIndex, int pageSize)
    {
        var count = source.Count;
        var items = source.Skip((pageIndex-1) * pageSize).Take(pageSize).ToList();
        return new SkillsViewModel(items, count, pageIndex, pageSize);
    }
}

LOT5RDB/Models/WeaponsViewModel.cs
using LOT5RDB.Equipment.Shared.Weapons.Models;

namespace LOT5RDB.Models;

public class WeaponsViewModel
{
    public WeaponsViewModel(List<WeaponModel> items, int count, int pageIndex, int pageSize)
    {
        PageIndex = pageIndex;
        TotalPages = (int) Math.Ceiling(count / (double) pageSize);

        Weapons = items;
    }
    
    public int PageIndex { get; private set; }
    public int TotalPages { get; private set; }
    public bool HasPreviousPage => PageIndex > 1;
    public bool HasNextPage => PageIndex < TotalPages;

    public List<WeaponModel> Weapons { get; set; }

    public static WeaponsViewModel Create(List<WeaponModel> source, int pageIndex, int pageSize)
    {
        var count = source.Count;
        var items = source.Skip((pageIndex-1) * pageSize).Take(pageSize).ToList();
        return new WeaponsViewModel(items, count, pageIndex, pageSize);
    }
}

LOT5RDB/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LOT5RDB.Models;

namespace LOT5RDB.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

LOT5RDB/Controllers/SkillsController.cs
using LOT5RDB.Models;
using LOT5RDB.Skills.Shared.Models;
using LOT5RDB.Skills.Shared.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace LOT5RDB.Controllers;

public class SkillsController : Controller
{
    private readonly IMediator _mediator;
    public SkillsController(IMediator mediator)
    {
        _mediator = mediator;

    }
    // GET
    public async Task<IActionResult> Index(string sortOrder, string currentFilter, string? searchString, int? pageNumber)
    {
        ViewData["CurrentSort"] = sortOrder;
        ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        ViewData["GroupSortParam"] = sortOrder == "Skill Group" ? "group_desc" : "Skill Group";
        var skills = await _mediator.Send(new GetSkillsQuery());
        if(!String.IsNullOrEmpty(searchString))
        {
            skills = skills.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper())
                                       || s.SkillGroup.Name.ToUpper().Contains(searchString.ToUpper()))
                .ToList();
        }

        if(searchString != null)
        {
            pageNumber = 1;
        }
        else
        {
            searchString = currentFilter;
        }

        List<SkillModel> sortedSkills;
        switch (sortOrder)
        {
            case "name_desc":
                sortedSkills = skills.OrderByDescending(s => s.Name).ToList();
                break;
            case "Skill Group":
                sortedSkills = skills.OrderBy(s => s.SkillGroup.Name).ToList();
                break;
            case "group_desc":
                sortedSkills = skills.OrderByDescending(s => s.SkillGroup.Name).ToList();
                break;
            default:
                sortedSkills = skills.OrderBy(s => s.Name).ToList();
                break;
        }
        return View(SkillsViewModel.Create(sortedSkills, pageNumber ?? 1, 5));
    }
    
    
}

LOT5RDB/Controllers/WeaponsController.cs
using LOT5RDB.Equipment.Shared.Weapons.Models;
using LOT5RDB.Equipment.Shared.Weapons.Queries;
using LOT5RDB.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace LOT5RDB.Controllers;

public class WeaponsController : Controller
{
    private readonly IMediator _mediator;
    public WeaponsController(IMediator mediator)
    {
        _mediator = mediator;

    }
    // GET
    public async Task<IActionResult> Index(string sortOrder, string currentFilter, string? searchString, int? pageNumber)
    {
        ViewData["CurrentSort"] = sortOrder;
        ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        var weapons = await _mediator.Send(new GetWeaponsQuery());
        weapons = FilterBySearchString(weapons, searchString);
        
        if(searchString != null)
        {
            pageNumber = 1;
        }
        else
        {
            searchString = currentFilter;
        }
        
        weapons = SortWeapons(weapons, sortOrder);

        return View(WeaponsViewModel.Create(weapons, pageNumber ?? 1, 5));
    }

    private static List<WeaponModel> FilterBySearchString(List<WeaponModel> weapons, string? searchString)
    {
        if(String.IsNullOrWhiteSpace(searchString))
        {
            return weapons;
        }

        return weapons.Where(w => w.Name.ToUpper().Contains(searchString.ToUpper())
                                  || w.Qualities.Any(q => q.Name.ToUpper().Contains(searchString.ToUpper()))
                                  || w.Skill.Name.ToUpper().Contains(searchString.ToUpper())).ToList();
    }

    private List<WeaponModel> SortWeapons(List<WeaponModel> weapons, string sortOrder)
    {
        switch (sortOrder)
        {
            case "name_desc":
                return weapons.OrderByDescending(w => w.Name).ToList();
            default:
                return weapons.OrderBy(w => w.Name).ToList();
        }
    }
}

LOT5RDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LOT5RDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - LOT5RDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/LOT5RDB.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LOT5RDB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Skills" asp-action="Index">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Weapons" asp-action="Index">Weapons</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - LOT5RDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LOT5RDB/Views/Skills/Index.cshtml
@model SkillsViewModel


<!DOCTYPE html>

<html lang="eng">
<head>
    <title>Skills</title>
</head>
<body>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" />
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Skill Name</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["GroupSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Skill Group</a>
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach(var skill in Model.Skills)
        {
            <tr>
                <td>@skill.Name</td>
                <td>@skill.SkillGroup.Name</td>
            </tr>
        }
        </tbody>
    </table>
    
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }
    
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    @Model.PageIndex
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>
</div>
</body>
</html>

LOT5RDB/Views/Weapons/Index.cshtml
@page
@model WeaponsViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>